server:
  port: 8182
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
jwt:
  secret: bbce7e869ae83a92d6c4d2c95bda94fa84f916208d5bb0fde7ba5aa34a9b8e0e
  expiration: 1800000
pagination:
  maxSize: ${PAGINATION_MAX_SIZE}