build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-cocktail-service:
  stage: test
  script:
    - echo "This job tests cocktail service"
    - cd cocktail-service
    - gradle clean test
    - tar -C build/reports/jacoco/test/ -czf jacoco_report.tar.gz .
    - tar -C build/reports/tests/ -czf gradle_report.tar.gz .

  artifacts:
    paths:
      - cocktail-service/jacoco_report.tar.gz
      - cocktail-service/gradle_report.tar.gz

test-party-service:
  stage: test
  script:
    - echo "This job tests party service"
    - cd party-service
    - gradle clean test
    - tar -C build/reports/jacoco/test/ -czf jacoco_report.tar.gz .
    - tar -C build/reports/tests/ -czf gradle_report.tar.gz .

  artifacts:
    paths:
      - cocktail-service/jacoco_report.tar.gz
      - cocktail-service/gradle_report.tar.gz

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
