server:
  port: 8182
spring:
  datasource:
    hikari:
      maximum-pool-size: 50
      connection-timeout: 6000
    url: jdbc:postgresql://postgres:5432/boozyCalc
    username: docker_user
    password: passphrase
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
jwt:
  secret: 443A84AE9B67A6D87BCFCE64F69B2
  expiration: 1800000
pagination:
  maxSize: ${PAGINATION_MAX_SIZE}

