server:
  port: 8183
spring:
  datasource:
    hikari:
      maximum-pool-size: 50
      connection-timeout: 6000
    url: jdbc:postgresql://prod_db:5432/boozyCalc
    username: docker_user
    password: passphrase
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  cloud:
    openfeign:
      client:
        config:
          auth:
            url: http://authapp:8182/
          cocktail:
            url: http://cocktailsapp:8181/
          product:
            url: http://cocktailsapp:8181/
          recipe:
            url: http://cocktailsapp:8181/
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
pagination:
  maxSize: ${PAGINATION_MAX_SIZE}

